ALTER TABLE PACIENTEEVOLUCAO ADD IDADE SMALLINT;
ALTER TABLE PACIENTEEVOLUCAO ADD ALTURA NUMERIC(12,4);
ALTER TABLE PACIENTEEVOLUCAO ADD PESO NUMERIC(12,4);
ALTER TABLE PACIENTEEVOLUCAO ADD IMC NUMERIC(12,4);
ALTER TABLE PACIENTEEVOLUCAO ADD TABAGISMO VARCHAR(250) CHARACTER SET WIN1252 COLLATE WIN_PTBR;
ALTER TABLE PACIENTEEVOLUCAO ADD DOENCASEMTRATAMENTO VARCHAR(250) CHARACTER SET WIN1252 COLLATE WIN_PTBR;
ALTER TABLE PACIENTEEVOLUCAO ADD ALERGIA VARCHAR(250) CHARACTER SET WIN1252 COLLATE WIN_PTBR;
ALTER TABLE PACIENTEEVOLUCAO ADD CIRURGIASPREVIA VARCHAR(250) CHARACTER SET WIN1252 COLLATE WIN_PTBR;
ALTER TABLE PACIENTEEVOLUCAO ADD QUEIXAPRINCIPAL VARCHAR(250) CHARACTER SET WIN1252 COLLATE WIN_PTBR;
ALTER TABLE PACIENTEEVOLUCAO ADD CONDUTA VARCHAR(250) CHARACTER SET WIN1252 COLLATE WIN_PTBR;

ALTER TABLE PACIENTE ADD INDICACAO VARCHAR(250) CHARACTER SET WIN1252 COLLATE WIN_PTBR;