
INSERT INTO SITUACAOREGISTRO (IDSITUACAOREGISTRO, DESCRICAO) VALUES (0, 'Inativo');
INSERT INTO SITUACAOREGISTRO (IDSITUACAOREGISTRO, DESCRICAO) VALUES (1, 'Ativo');


INSERT INTO VALORNAOSIM (IDVALORNAOSIM, DESCRICAO) VALUES (0, 'Não');
INSERT INTO VALORNAOSIM (IDVALORNAOSIM, DESCRICAO) VALUES (1, 'Sim');




INSERT INTO USUARIO (IDUSUARIO, IDPERFIL, IDSITUACAOREGISTRO, DATAINCLUSAO, LOGIN, SENHA) VALUES (0, 1, 1, '1-APR-2014', 'admin', 'sistema2010');
